apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: kubectl-deploy
  namespace: cicd
spec:
  params:
    - name: DEPLOYMENT
      type: string
      description: deployment name
    - name: NS
      type: string
      default: apps
      description: Namespace where the deployment resides
  steps:
    - name: run-kubectl 
      image: lachlanevenson/k8s-kubectl
      script: |
        kubectl -n $(params.NS) rollout restart deployment $(params.DEPLOYMENT)
