apiVersion: apps/v1
kind: Deployment
metadata:
  name: goserver-deployment
  namespace: apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: goserver
  template:
    metadata:
      labels:
        app: goserver
      namespace: apps
    spec:
      containers:
      - name: goserver
        image: ghcr.io/git-tux/goserver
        ports:
        - containerPort: 8000
